<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Authors>Filip Jeremic</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>A zero-dependency WPF control for displaying binary data in a traditional hex view.</Description>
    <PackageProjectUrl>https://github.com/fjeremic/HexView.Wpf</PackageProjectUrl>
    <RepositoryUrl>https://github.com/fjeremic/HexView.Wpf</RepositoryUrl>
    <RepositoryType>GitHub</RepositoryType>
    <PackageTags>WPF;HexView;HexViewer</PackageTags>
    <Version>0.2.0</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
